export var STATUS_SUCCESS = 'STATUS_SUCCESS';
export var STATUS_ERROR = 'STATUS_ERROR';
export var STATUS_WARNING = 'STATUS_WARNING';
export var STATUS_SCAN_ERROR = 'STATUS_SCAN_ERROR';
export var STATUS_LOADING = 'STATUS_LOADING';
export var STATUS_DEFAULT = 'STATUS_DEFAULT';
export var STATUS_NO_RESULTS = 'STATUS_NO_RESULTS';
export var DELAY = 2000;